# Generated by Django 3.2 on 2022-09-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='content',
            field=models.FileField(default='samples/sample_content.pdf', upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='contents',
            name='cover',
            field=models.ImageField(default='samples/sample_cover.jpeg', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
