# Generated by Django 3.2 on 2022-09-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20220909_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='book_id',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
