# Generated by Django 3.2 on 2022-09-12 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_alter_contents_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contents',
            old_name='content',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='contents',
            old_name='name',
            new_name='title',
        ),
    ]
