# Generated by Django 3.2 on 2022-09-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_auto_20220912_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='book_id',
            field=models.IntegerField(unique=True, verbose_name='id'),
        ),
    ]
